
// Generated by Cadence Genus(TM) Synthesis Solution 22.17-s071_1
// Generated on: Jul  8 2026 03:14:18 KST (Jul  7 2026 18:14:18 UTC)

// Verification Directory fv/comparator 

module comparator(i_a, i_b, o_equal, o_greater, o_less);
  input [3:0] i_a, i_b;
  output o_equal, o_greater, o_less;
  wire [3:0] i_a, i_b;
  wire o_equal, o_greater, o_less;
  wire n_0, n_1, n_2, n_3, n_4, n_5, n_6, n_7;
  wire n_8, n_9, n_10, n_11, n_12;
  NOR2XL g399__2398(.A (o_greater), .B (o_equal), .Y (o_less));
  NOR4X1 g400__5107(.A (n_10), .B (n_11), .C (n_6), .D (n_9), .Y
       (o_equal));
  NOR2XL g401__6260(.A (n_4), .B (n_12), .Y (o_greater));
  AOI2BB1XL g402__4319(.A0N (n_11), .A1N (n_8), .B0 (n_10), .Y (n_12));
  NAND3BXL g403__8428(.AN (n_5), .B (n_2), .C (n_7), .Y (n_9));
  AOI211XL g404__5526(.A0 (n_3), .A1 (n_7), .B0 (n_6), .C0 (n_1), .Y
       (n_8));
  OR3XL g405__6783(.A (n_0), .B (n_4), .C (n_3), .Y (n_5));
  INVXL g406(.A (n_1), .Y (n_2));
  NOR2BX1 g409__3680(.AN (i_a[3]), .B (i_b[3]), .Y (n_10));
  NOR2BX1 g408__1617(.AN (i_a[1]), .B (i_b[1]), .Y (n_1));
  NOR2BX1 g407__2802(.AN (i_a[0]), .B (i_b[0]), .Y (n_3));
  NOR2BX1 g410__1705(.AN (i_b[2]), .B (i_a[2]), .Y (n_11));
  NOR2BX1 g411__5122(.AN (i_b[0]), .B (i_a[0]), .Y (n_0));
  NOR2BX1 g412__8246(.AN (i_b[3]), .B (i_a[3]), .Y (n_4));
  NOR2BX1 g413__7098(.AN (i_a[2]), .B (i_b[2]), .Y (n_6));
  NAND2BXL g414__6131(.AN (i_a[1]), .B (i_b[1]), .Y (n_7));
endmodule

