
// Generated by Cadence Genus(TM) Synthesis Solution 22.17-s071_1
// Generated on: Jul  8 2026 03:22:55 KST (Jul  7 2026 18:22:55 UTC)

// Verification Directory fv/multiplexed_bus_driver 

module multiplexed_bus_driver(i_data_a, i_data_b, i_en_a, i_en_b,
     o_bus_data);
  input [7:0] i_data_a, i_data_b;
  input i_en_a, i_en_b;
  output [7:0] o_bus_data;
  wire [7:0] i_data_a, i_data_b;
  wire i_en_a, i_en_b;
  wire [7:0] o_bus_data;
  wire n_1, n_2, n_3, n_4, n_5, n_6, n_7, n_8;
  wire n_36;
  TBUFXL g11__2398(.A (n_5), .OE (n_36), .Y (o_bus_data[5]));
  TBUFXL g2__5107(.A (n_3), .OE (n_36), .Y (o_bus_data[6]));
  TBUFXL g10__6260(.A (n_2), .OE (n_36), .Y (o_bus_data[7]));
  TBUFXL g12__4319(.A (n_7), .OE (n_36), .Y (o_bus_data[4]));
  TBUFXL g15__8428(.A (n_1), .OE (n_36), .Y (o_bus_data[1]));
  TBUFXL g14__5526(.A (n_4), .OE (n_36), .Y (o_bus_data[2]));
  TBUFXL g13__6783(.A (n_6), .OE (n_36), .Y (o_bus_data[3]));
  TBUFXL g16__3680(.A (n_8), .OE (n_36), .Y (o_bus_data[0]));
  MX2X1 g267__2802(.A (i_data_b[0]), .B (i_data_a[0]), .S0 (i_en_a), .Y
       (n_8));
  MX2X1 g266__1705(.A (i_data_b[4]), .B (i_data_a[4]), .S0 (i_en_a), .Y
       (n_7));
  MX2X1 g270__5122(.A (i_data_b[3]), .B (i_data_a[3]), .S0 (i_en_a), .Y
       (n_6));
  MX2X1 g263__8246(.A (i_data_b[5]), .B (i_data_a[5]), .S0 (i_en_a), .Y
       (n_5));
  MX2X1 g262__7098(.A (i_data_b[2]), .B (i_data_a[2]), .S0 (i_en_a), .Y
       (n_4));
  MX2X1 g269__6131(.A (i_data_b[6]), .B (i_data_a[6]), .S0 (i_en_a), .Y
       (n_3));
  MX2X1 g268__1881(.A (i_data_b[7]), .B (i_data_a[7]), .S0 (i_en_a), .Y
       (n_2));
  MX2X1 g264__5115(.A (i_data_b[1]), .B (i_data_a[1]), .S0 (i_en_a), .Y
       (n_1));
  CLKXOR2X1 g2(.A (i_en_a), .B (i_en_b), .Y (n_36));
endmodule

