
// Generated by Cadence Genus(TM) Synthesis Solution 22.17-s071_1
// Generated on: Jul  8 2026 03:12:27 KST (Jul  7 2026 18:12:27 UTC)

// Verification Directory fv/bcd_to_7seg 

module bcd_to_7seg(i_bcd, o_seg);
  input [3:0] i_bcd;
  output [6:0] o_seg;
  wire [3:0] i_bcd;
  wire [6:0] o_seg;
  wire n_1, n_2, n_3, n_4, n_5, n_6, n_8, n_9;
  wire n_10, n_11, n_13, n_15, n_19, n_20, n_27;
  OAI22XL g336__2398(.A0 (n_9), .A1 (n_20), .B0 (n_10), .B1 (n_19), .Y
       (o_seg[0]));
  OAI21XL g338__5107(.A0 (n_5), .A1 (n_20), .B0 (n_19), .Y (o_seg[6]));
  OAI21XL g339__6260(.A0 (n_15), .A1 (n_20), .B0 (n_19), .Y (o_seg[3]));
  OR2X1 g342__4319(.A (n_3), .B (n_20), .Y (n_19));
  NOR2BX1 g340__8428(.AN (n_8), .B (n_20), .Y (o_seg[1]));
  OA21X1 g341__5526(.A0 (n_2), .A1 (n_15), .B0 (n_13), .Y (o_seg[5]));
  AND2XL g343__6783(.A (n_13), .B (n_11), .Y (o_seg[4]));
  OAI221X1 g337__3680(.A0 (i_bcd[0]), .A1 (n_4), .B0 (i_bcd[2]), .B1
       (n_27), .C0 (n_11), .Y (o_seg[2]));
  OAI31X1 g345__1617(.A0 (i_bcd[1]), .A1 (n_10), .A2 (n_1), .B0 (n_13),
       .Y (n_20));
  OA21X1 g344__2802(.A0 (i_bcd[0]), .A1 (n_6), .B0 (n_15), .Y (n_9));
  OR2X1 g347__1705(.A (i_bcd[0]), .B (n_8), .Y (n_11));
  OAI2BB1X1 g351__5122(.A0N (i_bcd[0]), .A1N (i_bcd[1]), .B0 (n_27), .Y
       (n_15));
  NAND2XL g349__8246(.A (i_bcd[1]), .B (n_6), .Y (n_8));
  INVXL g346(.A (n_27), .Y (n_5));
  NAND2XL g348__7098(.A (i_bcd[1]), .B (n_3), .Y (n_4));
  INVXL g353(.A (n_3), .Y (n_2));
  OAI21XL g350__6131(.A0 (i_bcd[1]), .A1 (i_bcd[2]), .B0 (i_bcd[3]), .Y
       (n_13));
  INVXL g354(.A (n_6), .Y (n_1));
  NOR2BX1 g355__5115(.AN (i_bcd[2]), .B (i_bcd[3]), .Y (n_3));
  NOR2XL g356__7482(.A (i_bcd[2]), .B (i_bcd[3]), .Y (n_6));
  INVXL g358(.A (i_bcd[0]), .Y (n_10));
  NAND2BX1 g2(.AN (i_bcd[1]), .B (n_10), .Y (n_27));
endmodule

